### ISSUE TITLE
maskAL for faster rcnn

### ISSUE THREAD

**Issue by pkhateri** [pieterblok/maskal#11]
Changing the `network_config` and the `pretrained_weights` to a `faster_rcnn` yaml file will generate an error message asking for a `mask_rcnn` config file. Does this mean that the AL is only implemented for mask rcnn models? Isn't it possible to run it for mere object detection with a faster rcnn model?

**Comment by pieterblok** [comment]
@pkhateri yes that is correct, MaskAL is only for Mask R-CNN. 

Last year I have developed BoxAL: active learning for Faster R-CNN. Yet, this software repository is still private, because we want to publish a scientific paper about it. For the moment, I have given you a personalized access to the BoxAL repository. 

Alternatively, you can also evaluate whether you want to use the active learning software from Lightly, this is based on YOLOv8: https://www.lightly.ai/post/active-learning-strategies-compared-for-yolov8-on-lincolnbeet

I hope one of those repositories works for you!

**Comment by pkhateri** [comment]
Thanks very much! I will check boxAL and let you know.

**Comment by pieterblok** [comment]
BoxAL is publicly available for this purpose:

https://github.com/pieterblok/boxal
