### ISSUE TITLE
Question: Dataset and config file

### ISSUE THREAD

**Issue by DeWildeDaan** [pieterblok/maskal#8]
I was wondering what dataset and configuration you used to get the results displayed in the documentation (maskAL_vs_random.png) and if you could share them with me?

**Comment by pieterblok** [comment]
> I was wondering what dataset and configuration you used to get the results displayed in the documentation (maskAL_vs_random.png) and if you could share them with me?

@DeWildeDaan this is a legitimate request! 

The configuration files can be found here:
https://github.com/pieterblok/maskal/blob/maskAL/active_learning/config/maskAL_experiment_uncertainty.yaml
https://github.com/pieterblok/maskal/blob/maskAL/active_learning/config/maskAL_experiment_random.yaml

The results were generated on a dataset with field-grown broccoli (containing healthy, diseased and defective broccoli heads). Unfortunately I cannot share this dataset, because it is proprietary (IP-related stuff). 

You might want to check whether you can replicate the results on MS-COCO or another open-source dataset with instance annotations. For instance the Trash Annotations in Context Dataset (TACO), which is weekly updated:
https://github.com/pedropro/TACO

**Comment by DeWildeDaan** [comment]
Thank you so much for the fast reply! 
I will try and reproduce the results with my own dataset.
